### ISSUE TITLE
[Devam S] Make an easter egg for the "All about the developers"

### ISSUE THREAD

**Issue by devamshri** [zenxha/kpop#14]
- [x] [Add it](https://github.com/zenxha/kpop/blob/main/views.py#L105-L120)  to 'add song' where if someone logs in with a specific username, then it redirects to the page
- [x] First add the html redirect page
- [x] Add the redirect feature.

**Comment by dylanroman** [comment]
Try to create a session separate from the default login session, and add a jinja "if" statement calling the session in html.

**Comment by lim04francis** [comment]
Ticket is geared towards PBL Task and will need code development/creation
Technicals will be able to be provided such as link to code, link to runtime, etc.

**Comment by sriyachilla** [comment]
I like that you specifically lay out all of the steps to complete your ticket. You are very specific in what you need to do, which will help you when you're working on the tickets. 10/10

**Comment by Chris-Ru** [comment]
5/5. Shows clear tangibles and redirects work as intended. Looks great on webpage and redirect feature seems to work when used.
