### ISSUE TITLE
Devam's Professional APCSP Prep

### ISSUE THREAD

**Issue by devamshri** [zenxha/kpop#15]
- [x] [2021 Test](https://docs.google.com/document/d/1XihJQyWcu1tcsdVXvy6uizGZ_yMuonbBw-0SLugeZeo/edit)
- [x] [2020 Test](https://docs.google.com/document/d/1XihJQyWcu1tcsdVXvy6uizGZ_yMuonbBw-0SLugeZeo/edit)
- [x] [Both Prep Books (I finished the whole book and did one of the practice tests)](https://documentcloud.adobe.com/link/track?uri=urn:aaid:scds:US:f4b48849-4f51-415f-93d7-724953fd0643#pageNum=1)
- [x] PORTFOLIO (Due Thursday!!!!)

**Comment by KrispyKremeSavage** [comment]
Verified by Eshaan Parlikar: 3/3
- has proof of taking both exams
- showed me portfolio code
- reliable proof for prep bookwork

**Comment by devamshri** [comment]
Self Grade: 3/3
I have evidence of completing the 2021 and 2020 exam, as well as a practice test from the review book. I also had the portfolio completed (which teacher can check I believe).

**Comment by jm1021** [comment]
Looks like you are on a heavy test prep path.  Seems like one of your test scores is great.  3/3 +2
