### ISSUE TITLE
[Eshaan] include secret page where reviews get sent

### ISSUE THREAD

**Issue by KrispyKremeSavage** [zenxha/kpop#17]
- [x] create [post button](https://github.com/zenxha/kpop/blob/main/templates/rate.html#L35-L48) to post reviews
- [x] establish [base of HTML](https://github.com/zenxha/kpop/blob/main/templates/display.html) for reviews posted
- Eshaan

**Comment by risaiwazaki** [comment]
This is a solid ticket. Maybe you could include a collaboration part where you work with your teammates on a portion of the proj. Other than that it looks good!

**Comment by MeganCorrigan** [comment]
These are pretty good! My only comment would to maybe be a bit more specific with like what the reviews will be for.

**Comment by notkobalt** [comment]
this is a really good ticket! i like that you made multiple bullets to account for everything you plan to do. a reasonable goal that you can complete for this week.

**Comment by devamshri** [comment]
5/5. Has tangibles which work on the website. Nice job!
