### ISSUE TITLE
[Eshaan] Prepare for AP Test

### ISSUE THREAD

**Issue by KrispyKremeSavage** [zenxha/kpop#18]
- [x] 2020 MC ([Reflection](https://docs.google.com/document/d/1eTJ5YifiMAN9x-PrXUkbdrsdcsE6qLF6TvIK-UdQzM0/edit?usp=sharing))
- [x] 2021 MC ([Completion Screenshot](https://docs.google.com/document/d/1HDNo9n0Ps8A4ZypFK7t_Ph06q8HqTVfZFxLDZT56rEU/edit?usp=sharing))
- [x] Create Task ([Code](https://docs.google.com/document/d/1YgQacPvM5uKh5rlJ-NG_2Q8O7WISJCNRdp17RkjUEfw/edit?usp=sharing))
- [x] Khan Academy Practice ([Screenshots of completion](https://docs.google.com/document/d/1CEjxGR5WzSlJ7jcNRk5yBCziw7gfkhHDAmpxzSc18i8/edit?usp=sharing))
- Eshaan

**Comment by KrispyKremeSavage** [comment]
Self-Grade: 3/3
-2 hours on 2021 MC 
-about 1 hour on 2020 MC
-3 hours on Create Task (specifically 1 hour on code)
-4 hours on Khan Academy practice

**Comment by devamshri** [comment]
good job Eshaan! Seems like you are putting in the hard work for the AP exam prep. Just a bit more AP exams over the weekend and a little review, and you should be good to go.

3/3

**Comment by jm1021** [comment]
Agree with Devam's comment.   Thanks for sharing you CB code.   I am curious how it will go as this is basic python but I believe it meets requireent.  3/3 +2
