### ISSUE TITLE
[Komay S] Use jquery and js to display random playlists on button click

### ISSUE THREAD

**Issue by zenxha** [zenxha/kpop#22]
- Execute function on the click [event](https://github.com/zenxha/kpop/blob/main/templates/index.html#L11)
- [Define ](https://github.com/zenxha/kpop/blob/main/templates/index.html#L45)function, function sends a [GET ](https://github.com/zenxha/kpop/blob/main/templates/index.html#L46)request to our [/api/random](https://github.com/zenxha/kpop/blob/main/view/api/app.py#L23-L37) endpoint, last week's ticket
-  api/random [runtime](http://rubinfamily.dyndns.org:5000/api/random)
-  function awaits json response, [parses and change](https://github.com/zenxha/kpop/blob/main/templates/index.html#L47-L51) site's html to display the new "random" playlist. [Runtime](http://rubinfamily.dyndns.org:5000/)

**Comment by 1855387** [comment]
Komay's execution of his ticket was done well. He provided ample links to code and runtime in order to fully showcase what he has been working on. Well done!
