### ISSUE TITLE
[Charlie Z] Add an About the Creators page

### ISSUE THREAD

**Issue by 1855387** [zenxha/kpop#23]
- [x] [Runtime](http://rubinfamily.dyndns.org:5000/aboutus) and [HTML file](https://github.com/zenxha/kpop/blob/main/templates/aboutus.html).
- [x] Work on understanding of [carousel and data slides](https://github.com/zenxha/kpop/blob/main/templates/aboutus.html#L33-L39) to make it easy to traverse through the different profiles.
- [x] Add unique profile pictures that each member wanted. [Folder storing images.](https://github.com/zenxha/kpop/tree/main/static/images)
- [x] Add the feature to the [main navigation bar](https://github.com/zenxha/kpop/tree/main/static/images) of the website. [App Route](https://github.com/zenxha/kpop/blob/main/views.py#L72-L74)
- [Upcoming ticket](https://github.com/zenxha/kpop/projects/2#card-61143461)

**Comment by zenxha** [comment]
5/5 Evaluation
- Tangibles and runtime all work as outlined in ticket
