### ISSUE TITLE
[Chris] Digital Portfolio & fill home page

### ISSUE THREAD

**Issue by Chris-Ru** [zenxha/kpop#5]
- [x] Digital Portfolio + [reference material](https://github.com/zenxha/kpop/blob/main/view/chris/algo/bubblesort.py) + [reference material runtime](http://rubinfamily.dyndns.org:5000/cr/bubble)
- [x] [Edit form](https://github.com/zenxha/kpop/blob/main/templates/index.html) on [submit page](http://rubinfamily.dyndns.org:5000/) with komay to make it look nicer

**Comment by zenxha** [comment]
Verified by Komay Sugiyama

**Comment by Chris-Ru** [comment]
Self-Grade: 3/3
- put approximately 2 hours into coding and customizing web page with quality work
- spent approximately 3 hours on digital portfolio and submitted early

**Comment by jm1021** [comment]
Agree with Komay's comments.  Thanks for code and runtime links.  Though on fill space? task that is a heck of a lot of CSS style code.  Is there a bootstrap way?   3/3 +1 as I have concern about CSS complexity.
