### ISSUE TITLE
[Chris R]Revising Code from last weeks CSS

### ISSUE THREAD

**Issue by Chris-Ru** [zenxha/kpop#7]
- [Previous week ticket](https://github.com/zenxha/kpop/issues/5)
- [x] [remove unnecessary/excessive CSS code](https://github.com/zenxha/kpop/blob/main/templates/submit.html#L66) and separate into a [separate CSS file](https://github.com/zenxha/kpop/blob/main/static/formstyle.css)
- [x] make subpage with [HTML base](https://github.com/zenxha/kpop/blob/main/templates/EaEggLabNav.html) for minilabs(essentially an easter egg

**Comment by MeganCorrigan** [comment]
is the CSS code for the entire project or a specific file?

**Comment by dylanroman** [comment]
CSS classes cut down on css the most, look into using the preset templates bootstrap uses through classes.

**Comment by MrMadman33** [comment]
Good ticket. Honing the website to achieve maximum efficiency is a great goal for improving on computer science engineering.

**Comment by devamshri** [comment]
5/5. Very nice job. Has tangibles and completely completes the ticket.

**Comment by KrispyKremeSavage** [comment]
5/5. Displays tangibles and shows proof of completing the ticket.
