### ISSUE TITLE
[Komay S] Setup API that returns random playlists

### ISSUE THREAD

**Issue by zenxha** [zenxha/kpop#8]
**Komay Sugiyama Ticket**

- [x] Create new [blueprint](https://github.com/zenxha/kpop/blob/main/view/api/app.py#L5) for api
ENDPOINTS: 
- [x] /api/random - returns a random playlist and the username from the database [CODE](https://github.com/zenxha/kpop/blob/main/view/api/app.py#L30-L37)
- [x] /api/all - Returns entire database as a list [CODE](https://github.com/zenxha/kpop/blob/main/view/api/app.py#L9-L22)
- [x] /api/playlist/id={USER_INPUTTED_INTEGER} - Returns playlist, username, and playlist name based on the user's provided integer [CODE](https://github.com/zenxha/kpop/blob/main/view/api/app.py#L39-L53)

**Comment by zenxha** [comment]
SELFGRADE **3/3**

**Comment by Chris-Ru** [comment]
Verified by Christopher Rubin 3/3
- Showed good effort and time spent on the creating API and individual webpages for API
- Multiple areas for tangibles which clarify what is happening with each part of the ticket

**Comment by jm1021** [comment]
This is a good looking Issue.  Work behind it looks like great database query code.  Very impressive  Only issue is missing runtime link 3/3 +1
