### ISSUE TITLE
[Charlie Z] Prepare for upcoming APCSP Test

### ISSUE THREAD

**Issue by 1855387** [zenxha/kpop#9]
- [x] 2020 Practice MC + Group Discussion + [Reflection](https://docs.google.com/document/d/1ektHWBniKtU0MGWwB5ULYK7O5T-lHBArJTQewhLD2wQ/edit)
- [x] 2021 [Practice MC](https://docs.google.com/document/d/1yZGh1fNDhvh7F4PlDYD5UjE0xf9mkLMSefzRVqsB4M4/edit) + Group Discussion
- [x] Extra practice from [Barron AP Exam practice](https://docs.google.com/document/d/101ejvO_E4a3wNk1uVVSnePA4FWAzS1ZEW2Wt8srTMw4/edit) textbook
- [x] Finish Create Task Responses Video and Code

**Comment by devamshri** [comment]
Overall, a solid 3/3 performance by Charlie over here. Seems like he met all of his goals which he wanted to and even took a picture of his completed test. Seems like he did a really good job with the test and just needs to do a little more prep for the exam.

**Comment by 1855387** [comment]
- around 2 or so hours working on the Video, response and code for the create task.
 - 2+ hours working on the diagnostic test in the book.
 - 1 hour looking up solutions and practice problems for concepts I got wrong.

**Comment by jm1021** [comment]
I agree with Devam, except I am not sure you need any more prep for exam.  Seems like you got it.  I am hoping to see you coding these last few weeks.  3/3 + 2
